create extension if not exists pgcrypto;

create table public.mahjong_effects (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('city', 'augment')),
  mode text not null check (mode in ('universal', 'longyan', 'xiamen')),
  rarity text check (rarity in ('silver', 'gold', 'prismatic')),
  name text not null,
  effect_text text not null,
  origin text not null,
  unique nulls not distinct (kind, mode, rarity, name)
);

create table public.mahjong_rooms (
  code text primary key check (code ~ '^[0-9]{6}$'),
  mode text not null check (mode in ('longyan', 'xiamen')),
  city jsonb not null,
  rarity text not null check (rarity in ('silver', 'gold', 'prismatic')),
  round integer not null default 1,
  host_token uuid not null,
  created_at timestamptz not null default now()
);

create table public.mahjong_room_players (
  room_code text not null references public.mahjong_rooms(code) on delete cascade,
  seat text not null check (seat in ('东', '南', '西', '北')),
  seat_token uuid not null,
  candidates jsonb not null,
  selected jsonb,
  joined_at timestamptz not null default now(),
  primary key (room_code, seat)
);

create index mahjong_rooms_created_at_idx on public.mahjong_rooms(created_at);

insert into public.mahjong_effects (kind, mode, rarity, name, effect_text, origin) values
  ('city','universal',null,'班德尔交换站','每位玩家本局第一次出牌前，可以重铸一张非金、非花手牌。','通用城邦'),
  ('city','universal',null,'铁匠工坊','本局首次完成杠牌的玩家获得一层护盾，每名玩家限一次。','通用城邦'),
  ('city','universal',null,'花神庭院','每名玩家本局补到第一张花时获得一层护盾。','通用城邦'),
  ('city','universal',null,'赏金码头','开场随机公布一种字牌；用它作将、刻子或杠并胡牌时额外获得一分。','通用城邦'),
  ('city','longyan',null,'分饼广场','本局第一次成功分饼时，完成跟牌的闲家各获得一层护盾。','龙岩专属'),
  ('city','longyan',null,'金色回廊','单游胡牌额外增加一分；双游、三游不重复增加。','龙岩专属'),
  ('city','longyan',null,'十三门','起手有五种不同幺九字牌获一层护盾；十三幺胡牌再加三分。','龙岩专属'),
  ('city','longyan',null,'抢杠峡谷','抢杠胡成功者额外获得一分，本局限一次。','龙岩专属'),
  ('city','xiamen',null,'鹭岛集市','本局第一次吃牌后，可以公开一张非金手牌并获得一层护盾。','厦门专属'),
  ('city','xiamen',null,'跟打长街','每名玩家本局第一次完成强制跟打时获得一层护盾。','厦门专属'),
  ('city','xiamen',null,'金门渡口','持金状态下自摸胡牌，倍率结算后额外增加一分。','厦门专属'),
  ('city','xiamen',null,'白鹭书院','白板以金牌原牌身份参与组牌并胡牌时，倍率结算后额外增加一分。','厦门专属'),
  ('augment','universal','silver','稳健经营','起手没有金时，第一次出牌前可重铸一张非金、非花手牌。','通用'),
  ('augment','universal','silver','庄家之徽','若本局是庄家，开局获得一层仅限本局的护盾。','通用'),
  ('augment','universal','silver','花开富贵','本局补到自己的第一张花时获得一层护盾。','通用'),
  ('augment','universal','gold','潘多拉手牌','本局第一次出牌前可以重铸一张非金、非花手牌。','通用'),
  ('augment','universal','gold','门清学派','未吃、碰、明杠并胡牌时额外获得一分。','通用'),
  ('augment','universal','gold','三色研究','胡牌时万、筒、条都至少组成一组面子，额外获得一分。','通用'),
  ('augment','universal','prismatic','四季同行','补到第二张花时获得一层护盾；集齐四季或四君子并胡牌再加两分。','通用'),
  ('augment','universal','prismatic','双重保险','本局第一次触发海克斯奖励时，可放弃奖励并改为获得两层护盾。','通用'),
  ('augment','universal','prismatic','后来居上','牌墙进入最后四分之一且尚未听牌时，获得一层仅限本局的护盾。','通用'),
  ('augment','longyan','silver','分饼大师','本局第一次成功参与分饼时获得一层护盾。','龙岩专属'),
  ('augment','longyan','silver','半自摸专家','本局普通自摸胡牌时额外获得一分。','龙岩专属'),
  ('augment','longyan','silver','金牌管理','本局第一次打出金牌后获得一层仅限本局的护盾。','龙岩专属'),
  ('augment','longyan','gold','金色单骑','单游胡牌时额外获得一分。','龙岩专属'),
  ('augment','longyan','gold','抢金先锋','抢金成功时额外获得一分。','龙岩专属'),
  ('augment','longyan','gold','无食专精','整局未碰、未明杠并胡牌时额外获得一分。','龙岩专属'),
  ('augment','longyan','prismatic','盖宝秘术','盖宝抢金成功时额外获得一分；发动失败则本局失效。','龙岩专属'),
  ('augment','longyan','prismatic','十三门徒','起手有五种不同幺九字牌获一层护盾；十三幺胡牌再加三分。','龙岩专属'),
  ('augment','longyan','prismatic','三重加冕','起手有两张金获一层护盾；三游胡牌再加三分。','龙岩专属'),
  ('augment','xiamen','silver','鹭岛食客','本局第一次吃牌后获得一层仅限本局的护盾。','厦门专属'),
  ('augment','xiamen','silver','跟打专家','本局第一次完成强制跟打后获得一层护盾。','厦门专属'),
  ('augment','xiamen','silver','平和防线','自己没有金时，本局点炮支付减少两分，最低减至零。','厦门专属'),
  ('augment','xiamen','gold','无金平和','无金状态下平胡，倍率结算后额外获得一分。','厦门专属'),
  ('augment','xiamen','gold','一金修行','恰好持有一张金并自摸，倍率结算后额外获得一分。','厦门专属'),
  ('augment','xiamen','gold','白板航标','白板以金牌原牌身份完成顺子并胡牌，额外获得一分。','厦门专属'),
  ('augment','xiamen','prismatic','门清鹭影','全局未吃、未碰、未明杠并胡牌时额外获得两分。','厦门专属'),
  ('augment','xiamen','prismatic','双游船票','起手有一张金获一层护盾；双游胡牌再加两分。','厦门专属'),
  ('augment','xiamen','prismatic','三游归航','起手有两张金获一层护盾；三游胡牌再加三分。','厦门专属');

create or replace function public.mahjong_pick_city(p_mode text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_mode text; v_effect public.mahjong_effects%rowtype;
begin
  v_mode := case when random() < 0.5 then 'universal' else p_mode end;
  select * into strict v_effect from public.mahjong_effects
    where kind = 'city' and mode = v_mode order by random() limit 1;
  return jsonb_build_object('name',v_effect.name,'effect',v_effect.effect_text,'origin',v_effect.origin);
end $$;

create or replace function public.mahjong_pick_rarity()
returns text language plpgsql volatile security definer set search_path = public as $$
declare v_roll double precision := random();
begin
  return case when v_roll < 0.5 then 'silver' when v_roll < 0.85 then 'gold' else 'prismatic' end;
end $$;

create or replace function public.mahjong_pick_candidates(p_mode text, p_rarity text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_first public.mahjong_effects%rowtype; v_second public.mahjong_effects%rowtype; v_third public.mahjong_effects%rowtype;
begin
  select * into strict v_first from public.mahjong_effects
    where kind='augment' and mode='universal' and rarity=p_rarity order by random() limit 1;
  select * into strict v_second from public.mahjong_effects
    where kind='augment' and mode=p_mode and rarity=p_rarity order by random() limit 1;
  select * into strict v_third from public.mahjong_effects
    where kind='augment' and mode in ('universal',p_mode) and rarity=p_rarity
      and name not in (v_first.name,v_second.name) order by random() limit 1;
  return jsonb_build_array(
    jsonb_build_object('name',v_first.name,'effect',v_first.effect_text,'origin',v_first.origin),
    jsonb_build_object('name',v_second.name,'effect',v_second.effect_text,'origin',v_second.origin),
    jsonb_build_object('name',v_third.name,'effect',v_third.effect_text,'origin',v_third.origin)
  );
end $$;

create or replace function public.mahjong_room_public(p_code text)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'code',r.code,'mode',r.mode,'city',r.city,'rarity',r.rarity,'round',r.round,
    'players',coalesce((
      select jsonb_agg(
        jsonb_build_object('seat',p.seat,'selected',p.selected)
        order by case p.seat when '东' then 1 when '南' then 2 when '西' then 3 else 4 end
      )
      from public.mahjong_room_players p where p.room_code=r.code
    ),'[]'::jsonb)
  ) from public.mahjong_rooms r where r.code=p_code;
$$;

create or replace function public.mahjong_create_room(p_mode text)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_code text; v_host uuid := gen_random_uuid(); v_inserted integer := 0; v_rarity text; v_try integer;
begin
  if p_mode not in ('longyan','xiamen') then raise exception 'invalid_mode'; end if;
  v_rarity := public.mahjong_pick_rarity();
  for v_try in 1..20 loop
    v_code := lpad(floor(random()*1000000)::integer::text,6,'0');
    insert into public.mahjong_rooms(code,mode,city,rarity,host_token)
      values(v_code,p_mode,public.mahjong_pick_city(p_mode),v_rarity,v_host)
      on conflict do nothing;
    get diagnostics v_inserted = row_count;
    exit when v_inserted = 1;
  end loop;
  if v_inserted <> 1 then raise exception 'room_creation_failed'; end if;
  return jsonb_build_object('room',public.mahjong_room_public(v_code),'hostToken',v_host::text);
end $$;

create or replace function public.mahjong_get_room(p_code text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_room jsonb;
begin
  v_room := public.mahjong_room_public(p_code);
  if v_room is null then raise exception 'room_not_found'; end if;
  return jsonb_build_object('room',v_room);
end $$;

create or replace function public.mahjong_join_room(p_code text, p_seat text, p_token uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_room public.mahjong_rooms%rowtype; v_player public.mahjong_room_players%rowtype;
begin
  if p_seat not in ('东','南','西','北') then raise exception 'invalid_seat'; end if;
  select * into v_room from public.mahjong_rooms where code=p_code;
  if not found then raise exception 'room_not_found'; end if;
  insert into public.mahjong_room_players(room_code,seat,seat_token,candidates)
    values(p_code,p_seat,p_token,public.mahjong_pick_candidates(v_room.mode,v_room.rarity))
    on conflict do nothing;
  select * into strict v_player from public.mahjong_room_players where room_code=p_code and seat=p_seat;
  if v_player.seat_token <> p_token then raise exception 'seat_taken'; end if;
  return jsonb_build_object('seat',v_player.seat,'candidates',v_player.candidates,'selected',v_player.selected,'round',v_room.round);
end $$;

create or replace function public.mahjong_select_hex(p_code text, p_seat text, p_token uuid, p_choice_index integer)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_player public.mahjong_room_players%rowtype; v_choice jsonb;
begin
  select * into v_player from public.mahjong_room_players where room_code=p_code and seat=p_seat;
  if not found or v_player.seat_token <> p_token then raise exception 'seat_verification_failed'; end if;
  if v_player.selected is not null then raise exception 'already_selected'; end if;
  if p_choice_index not between 0 and 2 then raise exception 'invalid_choice'; end if;
  v_choice := v_player.candidates -> p_choice_index;
  if v_choice is null then raise exception 'invalid_choice'; end if;
  update public.mahjong_room_players set selected=v_choice where room_code=p_code and seat=p_seat;
  return jsonb_build_object('selected',v_choice);
end $$;

create or replace function public.mahjong_next_round(p_code text, p_host_token uuid)
returns jsonb language plpgsql volatile security definer set search_path = public as $$
declare v_room public.mahjong_rooms%rowtype; v_rarity text;
begin
  select * into v_room from public.mahjong_rooms where code=p_code;
  if not found then raise exception 'room_not_found'; end if;
  if v_room.host_token <> p_host_token then raise exception 'host_verification_failed'; end if;
  v_rarity := public.mahjong_pick_rarity();
  update public.mahjong_rooms
    set city=public.mahjong_pick_city(v_room.mode),rarity=v_rarity,round=round+1
    where code=p_code;
  update public.mahjong_room_players
    set candidates=public.mahjong_pick_candidates(v_room.mode,v_rarity),selected=null
    where room_code=p_code;
  return jsonb_build_object('ok',true,'round',v_room.round+1);
end $$;

alter table public.mahjong_effects enable row level security;
alter table public.mahjong_rooms enable row level security;
alter table public.mahjong_room_players enable row level security;

revoke all on public.mahjong_effects, public.mahjong_rooms, public.mahjong_room_players from anon, authenticated;
revoke all on sequence public.mahjong_effects_id_seq from anon, authenticated;
revoke all on function public.mahjong_pick_city(text) from public, anon, authenticated;
revoke all on function public.mahjong_pick_rarity() from public, anon, authenticated;
revoke all on function public.mahjong_pick_candidates(text,text) from public, anon, authenticated;
revoke all on function public.mahjong_room_public(text) from public, anon, authenticated;
revoke all on function public.mahjong_create_room(text) from public, anon, authenticated;
revoke all on function public.mahjong_get_room(text) from public, anon, authenticated;
revoke all on function public.mahjong_join_room(text,text,uuid) from public, anon, authenticated;
revoke all on function public.mahjong_select_hex(text,text,uuid,integer) from public, anon, authenticated;
revoke all on function public.mahjong_next_round(text,uuid) from public, anon, authenticated;
grant execute on function public.mahjong_create_room(text) to anon, authenticated;
grant execute on function public.mahjong_get_room(text) to anon, authenticated;
grant execute on function public.mahjong_join_room(text,text,uuid) to anon, authenticated;
grant execute on function public.mahjong_select_hex(text,text,uuid,integer) to anon, authenticated;
grant execute on function public.mahjong_next_round(text,uuid) to anon, authenticated;
